// <auto-generated />
using System;
using CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240829083907_inital2")]
    partial class inital2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Name = "10% OFF",
                            Percent = 10
                        },
                        new
                        {
                            ID = 2,
                            IsActive = false,
                            Name = "15% OFF",
                            Percent = 15
                        },
                        new
                        {
                            ID = 3,
                            IsActive = false,
                            Name = "20% OFF",
                            Percent = 20
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            Name = "25% OFF",
                            Percent = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
